=== MoreiraJorge/PDE/Trabalho 1/DTD/guiao.dtd
<!ENTITY % TXT "#PCDATA">

<!-- CabeÃ§alho-->
<!ELEMENT guiao (cabecalho, historia)>

<!ELEMENT cabecalho (titulo, (autor | autores), data, sinopse?, personagens, aderecos)>
<!ELEMENT historia (temporada+ | parte+ | cena+) >

<!ELEMENT titulo (%TXT;)>
<!ELEMENT autores (autor)+>
<!ELEMENT autor (%TXT;)>

<!ELEMENT data ( ano , mes , dia )>
<!ELEMENT ano (%TXT;)>
<!ELEMENT mes (%TXT;)>
<!ELEMENT dia (%TXT;)>

<!ELEMENT sinopse (%TXT;)>

<!ELEMENT personagens (personagem)+>
<!ELEMENT personagem (%TXT;)>
<!ATTLIST personagem id ID #REQUIRED
                     descricao CDATA #REQUIRED>

<!ELEMENT nome (%TXT;)>
<!ELEMENT descricao (%TXT;)>

<!-- Hierarquia-->
<!ELEMENT temporada ((personagem | personagens)?, episodio+)>

<!ELEMENT episodio ((personagem | personagens)?, (parte+ | cena+))>

<!ELEMENT parte ((personagem | personagens)?, cena+)>

<!ELEMENT cena ( %TXT; | fala | refere | comentario | refAdereco)*>
<!ATTLIST cena contexto CDATA #REQUIRED>

<!ELEMENT fala (%TXT;)>
<!ATTLIST fala ref-personagem IDREF #REQUIRED>

<!ELEMENT comentario (%TXT;)>

<!ELEMENT refere EMPTY>
<!ATTLIST refere ref-personagem IDREF #REQUIRED>

<!ELEMENT aderecos (adereco)+>

<!ELEMENT adereco (%TXT;)>
<!ATTLIST adereco id ID #REQUIRED>

<!ELEMENT refAdereco EMPTY>
<!ATTLIST refAdereco ref-adereco IDREF #REQUIRED>

=== MoreiraJorge/PDE/Trabalho 1/DTD/Exemplo/guiao2.xml
<?xml version="1.1" encoding="UTF-8" standalone="no"?>
<!DOCTYPE guiao SYSTEM "../guiao.dtd" [
    <!ENTITY aderecos SYSTEM "aderecos.xml">
    <!ENTITY personagens SYSTEM "personagens.xml">
]>

<guiao>
    <cabecalho>
        <titulo>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</titulo>
        <autores>
            <autor>Jorge</autor>
            <autor>Joaquim</autor>
        </autores>
        <data>
            <ano>2020</ano>
            <mes>01</mes>
            <dia>10</dia>
        </data>
        <sinopse>It is a long established fact that a reader will be distracted by the readable
            content of a page when looking at its layout. The point of using Lorem Ipsum is that it
            has a more-or-less normal distribution of letters, as opposed to using 'Content here,
            content here', making it look like readable English. Many desktop publishing packages
            and web page editors now use Lorem Ipsum as their default model text, and a search for
            'lorem ipsum' will uncover many web sites still in their infancy. Various versions have
            evolved over the years, sometimes by accident, sometimes on purpose (injected humour and
            the like). </sinopse>
        &personagens;
        &aderecos;
    </cabecalho>
    <conteudo>
        <parte>
            <personagem id="p3" descricao="personagem papagaio">Faisca</personagem>
            <cena
                contexto="Durante uma navregação pelo mar mediterâneo um pirata malvado avistou o navio de um capitão valente"
                > Durante uma tempestadde maritima do mar mediterraneo o <refere ref-personagem="p1"
                /> avistou um navio à distãncia que pertencia ao <refere ref-personagem="p2"/> .
                Durante esta descoberta o <refere ref-personagem="p1"/> disse ao <refere
                    ref-personagem="p3"/> : <fala ref-personagem="p1">
                    <refere ref-personagem="p3"/> , buscar a minha <adereco ref-adereco="adr2"/> ! </fala>
                <comentario>O papagaio voa para até ela</comentario> Entretanto o <refere
                    ref-personagem="p2"/> preparava o seu <adereco ref-adereco="adr3"/> para
                atacar... </cena>
        </parte>
    </conteudo>
</guiao>

=== MoreiraJorge/PDE/Trabalho 1/DTD/guiao3.xml
<?xml version="1.1" encoding="UTF-8" standalone="no"?>
<!DOCTYPE guiao SYSTEM "guiao.dtd" [
    <!ENTITY aderecos SYSTEM "aderecos.xml">
    <!ENTITY personagens SYSTEM "personagens.xml">
]>

<guiao>
    <cabecalho>
        <titulo>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</titulo>
        <autores>
            <autor>Manel Da Vinha</autor>
            <autor>To Ze Antonio</autor>
        </autores>
        <data>
            <ano>2020</ano>
            <mes>01</mes>
            <dia>10</dia>
        </data>
        <sinopse>It is a long established fact that a reader will be distracted by the readable
            content of a page when looking at its layout. The point of using Lorem Ipsum is that it
            has a more-or-less normal distribution of letters, as opposed to using 'Content here,
            content here', making it look like readable English. Many desktop publishing packages
            and web page editors now use Lorem Ipsum as their default model text, and a search for
            'lorem ipsum' will uncover many web sites still in their infancy. Various versions have
            evolved over the years, sometimes by accident, sometimes on purpose (injected humour and
            the like). </sinopse>
        &personagens;
        &aderecos;
    </cabecalho>
    <conteudo>
        <cena contexto="A caminhar na rua"> Numa caminhada matinal <comentario> O Quim cai </comentario>
            <fala ref-personagem="p1"> Que caraças Jorge</fala> pega na <adereco
                ref-adereco="adr1"/> para matar o <refere ref-personagem="p2"/>. E o Jorge fugiu. </cena>
        <cena contexto="A caminhar na rua"> Numa caminhada matinal <comentario> O Quim cai </comentario>
            <fala ref-personagem="p1"> Que caraças Jorge</fala> pega na <adereco
                ref-adereco="adr1"/> para matar o <refere ref-personagem="p2"/>. E o Jorge fugiu.
        </cena>
    </conteudo>
</guiao>
